name: Build and Deploy Dockerized App to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and tag Docker image
        run: docker build -t car-max-app .

      - name: Deploy container using Dockerfile
        uses: azure/webapps-deploy@v2
        with:
          app-name: car-max-saif123
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: DOCKER|car-max-app
